/**
 * Renders the two generated reference pages — `docs/tools.md` and
 * `docs/rule-packs.md` — from the things they describe: the registered MCP
 * surface and the Semgrep pack files. Pure: every input is passed in, so the
 * drift test (`docs.test.ts`) and the writer (`generateDocs.ts`, run by
 * `npm run build`) produce the same bytes from the same source.
 *
 * Why generated at all: every hand-maintained copy of these facts drifted.
 * The README said 57 tools while CLAUDE.md said 54 and `mcp/README.md` said
 * both; CLAUDE.md's pack table said 134 rules across nine packs after a tenth
 * pack had shipped. A page that is derived cannot say anything the registry
 * or the pack files do not.
 *
 * Lives under `test/` for the reason `test/ablate/` does: it is developer
 * tooling that must never reach `dist/`, and `tsconfig.test.json` already
 * type-checks this tree at full strictness. It is not a vitest test (the
 * collector only takes `*.test.ts`).
 */

import type { ZodTypeAny } from 'zod';
import type { ResourceModule } from '../../src/resources/index.js';
import type { ToolModule } from '../../src/tools/index.js';
import type { RuleInventory } from '../ablate/clauses.js';

/** The line every generated page starts with, after its title. */
export const GENERATED_NOTICE =
  '<!-- Generated by `npm run build` (mcp/test/docs/generate.ts). Do not edit by hand. -->';

// ------------------------------------------------------------- markdown text

/**
 * Escape prose for Markdown while keeping its backtick code spans intact.
 * Outside a code span, characters Markdown would read as syntax are escaped
 * (`*`, `_`, `[`, `]`, `\`) and angle brackets become entities, so a path
 * like `reports/sast-<scan>/` is never parsed as an HTML tag. With `inTable`,
 * pipes are escaped everywhere — GFM splits cells on `|` even inside a code
 * span, and reads `\|` there as a literal pipe.
 */
export function escapeInline(text: string, inTable = false): string {
  const oneLine = text.replace(/\r?\n+/g, ' ');
  const parts = oneLine.split('`');
  // An odd number of backticks leaves one unpaired: treat the whole string as
  // prose, backticks included, rather than guess where a span ends.
  if (parts.length % 2 === 0) return escapeProse(oneLine.replace(/`/g, '\\`'), inTable);
  return parts
    .map((part, i) => (i % 2 === 1 ? `\`${inTable ? part.replace(/\|/g, '\\|') : part}\`` : escapeProse(part, inTable)))
    .join('');
}

/** A URL in prose becomes a code span: a bare one would be auto-linked. */
const URL_IN_PROSE = /(https?:\/\/[^\s`)]+[^\s`).,;:])/;

function escapeProse(text: string, inTable: boolean): string {
  return text
    .split(URL_IN_PROSE)
    .map((piece, i) => {
      if (i % 2 === 1) return `\`${inTable ? piece.replace(/\|/g, '\\|') : piece}\``;
      let out = piece
        .replace(/\\(?!`)/g, '\\\\')
        .replace(/([*_[\]])/g, '\\$1')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
      if (inTable) out = out.replace(/\|/g, '\\|');
      return out;
    })
    .join('');
}

// ------------------------------------------------------------ zod parameters

interface ZodDefLike {
  typeName?: string;
  description?: string;
  innerType?: ZodTypeAny;
  schema?: ZodTypeAny;
  type?: ZodTypeAny;
  values?: unknown;
  value?: unknown;
  options?: unknown;
  shape?: () => Record<string, ZodTypeAny>;
  defaultValue?: () => unknown;
  valueType?: ZodTypeAny;
}

function def(t: ZodTypeAny): ZodDefLike {
  return t._def as ZodDefLike;
}

const WRAPPERS = new Set(['ZodOptional', 'ZodDefault', 'ZodNullable', 'ZodEffects', 'ZodReadonly', 'ZodBranded']);

/** Strip optional / default / nullable / effects wrappers. */
function unwrap(t: ZodTypeAny): ZodTypeAny {
  let cur = t;
  for (;;) {
    const d = def(cur);
    if (d.typeName === undefined || !WRAPPERS.has(d.typeName)) return cur;
    const next = d.innerType ?? d.schema ?? d.type;
    if (next === undefined) return cur;
    cur = next;
  }
}

/** The first `.describe()` text found walking in through the wrappers. */
function descriptionOf(t: ZodTypeAny): string {
  let cur: ZodTypeAny | undefined = t;
  while (cur !== undefined) {
    const d = def(cur);
    if (typeof d.description === 'string' && d.description.trim() !== '') return d.description.trim();
    if (d.typeName === undefined || !WRAPPERS.has(d.typeName)) return '';
    cur = d.innerType ?? d.schema ?? d.type;
  }
  return '';
}

/** A `.default()` anywhere in the wrapper chain, rendered as JSON. */
function defaultOf(t: ZodTypeAny): string | undefined {
  let cur: ZodTypeAny | undefined = t;
  while (cur !== undefined) {
    const d = def(cur);
    if (d.typeName === 'ZodDefault' && d.defaultValue !== undefined) return JSON.stringify(d.defaultValue());
    if (d.typeName === undefined || !WRAPPERS.has(d.typeName)) return undefined;
    cur = d.innerType ?? d.schema ?? d.type;
  }
  return undefined;
}

/** A short, pipe-free type label. */
export function typeLabel(t: ZodTypeAny): string {
  const inner = unwrap(t);
  const d = def(inner);
  switch (d.typeName) {
    case 'ZodString':
      return 'string';
    case 'ZodNumber':
      return 'number';
    case 'ZodBoolean':
      return 'boolean';
    case 'ZodEnum':
      return Array.isArray(d.values) ? `one of ${d.values.map((v) => `"${String(v)}"`).join(', ')}` : 'enum';
    case 'ZodLiteral':
      return JSON.stringify(d.value);
    case 'ZodArray':
      return d.type !== undefined ? `array of ${typeLabel(d.type)}` : 'array';
    case 'ZodObject':
      return 'object';
    case 'ZodRecord':
      return d.valueType !== undefined ? `map of ${typeLabel(d.valueType)}` : 'map';
    case 'ZodUnion':
      return Array.isArray(d.options) ? (d.options as ZodTypeAny[]).map((o) => typeLabel(o)).join(' or ') : 'union';
    default:
      return (d.typeName ?? 'unknown').replace(/^Zod/, '').toLowerCase();
  }
}

export interface ParamRow {
  /** Dotted path for nested object members: `scope.diff.base`. */
  path: string;
  type: string;
  required: boolean;
  default?: string;
  description: string;
}

/** Every parameter of a raw zod shape, nested object members included. */
export function paramRows(shape: Record<string, ZodTypeAny>, prefix = ''): ParamRow[] {
  const rows: ParamRow[] = [];
  for (const [key, field] of Object.entries(shape)) {
    const path = prefix === '' ? key : `${prefix}.${key}`;
    const dflt = defaultOf(field);
    rows.push({
      path,
      type: typeLabel(field),
      required: !field.isOptional(),
      ...(dflt !== undefined ? { default: dflt } : {}),
      description: descriptionOf(field),
    });
    const inner = def(unwrap(field));
    if (inner.typeName === 'ZodObject' && inner.shape !== undefined) rows.push(...paramRows(inner.shape(), path));
  }
  return rows;
}

// ---------------------------------------------------------------- tools page

export function renderToolsDoc(tools: readonly ToolModule[], resources: readonly ResourceModule[]): string {
  const sortedTools = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  const sortedResources = [...resources].sort((a, b) => a.uri.localeCompare(b.uri));
  const out: string[] = [];

  out.push('# MCP tools and resources', '', GENERATED_NOTICE, '');
  out.push(
    `The dev-guardian MCP server registers **${tools.length} tools** and **${resources.length} resources**. ` +
      'This page is rendered from the registry itself (`mcp/src/registerAll.ts`): every description and ' +
      'parameter below is exactly what an MCP host receives. For which tool to reach for, see ' +
      '[`host-rules/AGENTS.md`](../host-rules/AGENTS.md); for the slash commands that drive them, the ' +
      '[README](../README.md).',
    '',
  );

  out.push('## Index', '', '| Tool | Title | Parameters |', '| --- | --- | --- |');
  for (const t of sortedTools) {
    const names = Object.keys(t.inputSchema);
    const params = names.length === 0 ? '—' : names.map((n) => `\`${n}\``).join(', ');
    const title = t.title !== undefined && t.title.trim() !== '' ? escapeInline(t.title, true) : '—';
    out.push(`| [\`${t.name}\`](#${t.name}) | ${title} | ${params} |`);
  }
  out.push('');

  out.push('## Tools', '');
  for (const t of sortedTools) {
    out.push(`### \`${t.name}\``, '');
    out.push(escapeInline(t.description), '');
    const rows = paramRows(t.inputSchema);
    if (rows.length === 0) {
      out.push('No parameters.', '');
      continue;
    }
    out.push('| Parameter | Type | Required | Default | Description |', '| --- | --- | --- | --- | --- |');
    for (const r of rows) {
      out.push(
        `| \`${r.path}\` | ${escapeInline(r.type, true)} | ${r.required ? 'yes' : 'no'} | ` +
          `${r.default !== undefined ? `\`${r.default.replace(/\|/g, '\\|')}\`` : '—'} | ` +
          `${r.description === '' ? '—' : escapeInline(r.description, true)} |`,
      );
    }
    out.push('');
  }

  out.push('## Resources', '');
  out.push(
    'Every resource returns compact JSON and answers for the project the server was started in.',
    '',
    '| URI | Name | Description |',
    '| --- | --- | --- |',
  );
  for (const r of sortedResources) {
    out.push(`| \`${r.uri.replace(/\|/g, '\\|')}\` | \`${r.name}\` | ${escapeInline(r.description, true)} |`);
  }
  out.push('');
  return out.join('\n');
}

// ----------------------------------------------------------- rule-packs page

export interface PackInput {
  /** File name under `configs/semgrep/`, e.g. `bugfix-js.yml`. */
  file: string;
  /** Rules in source order: id, severity and languages as written. */
  rules: readonly { id: string; severity: string; languages: readonly string[] }[];
  /** `enumerateClauses(source).rules`, same order as `rules`. */
  inventory: readonly RuleInventory[];
}

/** Which tool loads each pack. Checked against the pack list by the test. */
export const PACK_CONSUMERS: Readonly<Record<string, string>> = {
  'base.yml': '`scan_sast`, once `init_project` has installed it as the project\'s `.semgrep.yml`',
  'bugfix-cs.yml': '`bug_hunt`',
  'bugfix-go.yml': '`bug_hunt`',
  'bugfix-java.yml': '`bug_hunt`',
  'bugfix-js.yml': '`bug_hunt`',
  'bugfix-php.yml': '`bug_hunt`',
  'bugfix-py.yml': '`bug_hunt`',
  'bugfix-rs.yml': '`bug_hunt`',
  'llm.yml': '`scan_sast` (and so `security_scan_full` and `review_pr`), on every Semgrep run, the Docker fallback included',
  'web-js.yml': '`scan_sast` (and so `security_scan_full` and `review_pr`), on every Semgrep run, the Docker fallback included',
  'rgpd.yml':'`compliance_check`',
  'routes.yml': '`map_attack_surface` (and so `scan_dast` and `validate_finding`)',
};

export type NoClauseKind = 'bare' | 'positive-only' | 'other';

/** Classify a rule with no ablatable clause by the harness's own reason text. */
export function noClauseKind(reason: string): NoClauseKind {
  if (/^a bare /.test(reason)) return 'bare';
  if (/only positive terms/.test(reason)) return 'positive-only';
  return 'other';
}

export interface PackTotals {
  packs: number;
  rules: number;
  withClauses: number;
  withNone: number;
  bare: number;
  positiveOnly: number;
}

export function packTotals(packs: readonly PackInput[]): PackTotals {
  const inv = packs.flatMap((p) => p.inventory);
  const none = inv.filter((r) => r.clauseCount === 0);
  return {
    packs: packs.length,
    rules: inv.length,
    withClauses: inv.length - none.length,
    withNone: none.length,
    bare: none.filter((r) => noClauseKind(r.noClausesReason ?? '') === 'bare').length,
    positiveOnly: none.filter((r) => noClauseKind(r.noClausesReason ?? '') === 'positive-only').length,
  };
}

function uniqueSorted(values: Iterable<string>): string[] {
  return [...new Set(values)].sort();
}

function countBy(values: readonly string[]): string {
  const counts = new Map<string, number>();
  for (const v of values) counts.set(v, (counts.get(v) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([k, n]) => `${n} ${k}`)
    .join(', ');
}

export function renderRulePacksDoc(packs: readonly PackInput[]): string {
  const sorted = [...packs].sort((a, b) => a.file.localeCompare(b.file));
  const totals = packTotals(sorted);
  const out: string[] = [];

  out.push('# Semgrep rule packs', '', GENERATED_NOTICE, '');
  out.push(
    `dev-guardian ships **${totals.rules} rules in ${totals.packs} packs** under ` +
      '[`configs/semgrep/`](../configs/semgrep/). Messages and comments are in Portuguese; each pack\'s ' +
      'header comment records what was measured, against which corpus, and why each exclusion exists.',
    '',
    `**${totals.withNone} of the ${totals.rules} rules** have no clause the ablation harness ` +
      `(\`npm run ablate\`, see [CLAUDE.md](../CLAUDE.md)) can remove — ${totals.bare} are a bare ` +
      `\`pattern\` / \`pattern-regex\` and ${totals.positiveOnly} a \`patterns\` group of positive terms only. ` +
      'Those rules are checked by axis 0 (the rule fires on its `hits/` fixtures) and nothing else.',
    '',
  );

  out.push(
    '| Pack | Run by | Rules | With ablatable clauses | With none | Languages | Severity |',
    '| --- | --- | ---: | ---: | ---: | --- | --- |',
  );
  for (const p of sorted) {
    const withNone = p.inventory.filter((r) => r.clauseCount === 0).length;
    const langs = uniqueSorted(p.rules.flatMap((r) => r.languages)).join(', ');
    out.push(
      `| [\`${p.file.replace(/\.yml$/, '')}\`](#${p.file.replace(/\.yml$/, '')}) | ${PACK_CONSUMERS[p.file] ?? '—'} | ` +
        `${p.rules.length} | ${p.rules.length - withNone} | ${withNone} | ${langs} | ` +
        `${countBy(p.rules.map((r) => r.severity))} |`,
    );
  }
  out.push(
    `| **total** | | **${totals.rules}** | **${totals.withClauses}** | **${totals.withNone}** | | |`,
    '',
  );

  for (const p of sorted) {
    const name = p.file.replace(/\.yml$/, '');
    out.push(`## ${name}`, '');
    out.push(`[\`configs/semgrep/${p.file}\`](../configs/semgrep/${p.file}) — run by ${PACK_CONSUMERS[p.file] ?? '—'}.`, '');
    out.push('| Rule | Severity | Languages | Ablatable clauses |', '| --- | --- | --- | --- |');
    p.rules.forEach((r, i) => {
      const inv = p.inventory[i];
      const clauses =
        inv === undefined
          ? '—'
          : inv.clauseCount > 0
            ? String(inv.clauseCount)
            : `0 (${noClauseKind(inv.noClausesReason ?? '') === 'other' ? 'none' : noClauseKind(inv.noClausesReason ?? '')})`;
      out.push(`| \`${r.id}\` | ${r.severity} | ${r.languages.join(', ')} | ${clauses} |`);
    });
    out.push('');
  }
  return out.join('\n');
}
