import { describe, expect, it } from 'vitest';
import { actionlintParser } from '../../../../src/runners/scannerParsers/actionlint.js';

// Real shape, from rhysd/actionlint's own `testdata/format/test.json`
// (generated by `actionlint -pyflakes= -shellcheck= -format '{{json .}}'`).
const SAMPLE = JSON.stringify([
  {
    message:
      'unexpected key "branch" for "push" section. expected one of "branches", "branches-ignore", "paths", "paths-ignore", "tags", "tags-ignore", "types", "workflows"',
    filepath: '.github/workflows/ci.yml',
    line: 3,
    column: 5,
    kind: 'syntax-check',
    snippet: '    branch: main\n    ^~~~~~~',
    end_column: 11,
  },
  {
    message: 'property "msg" is not defined in object type {}',
    filepath: '.github/workflows/ci.yml',
    line: 9,
    column: 23,
    kind: 'expression',
    snippet: '      - run: echo ${{ matrix.msg }}\n                      ^~~~~~~~~~',
    end_column: 32,
  },
]);

describe('actionlintParser', () => {
  it('produces one Finding per entry', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    expect(findings).toHaveLength(2);
  });

  it('uses category=security, subcategory=ci, tool=actionlint', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    expect(findings.every((f) => f.category === 'security')).toBe(true);
    expect(findings.every((f) => f.subcategory === 'ci')).toBe(true);
    expect(findings.every((f) => f.tool === 'actionlint')).toBe(true);
  });

  it('has no native severity, so every finding defaults to medium', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    expect(findings.every((f) => f.severity === 'medium')).toBe(true);
  });

  it('maps kind to rule_id', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    expect(findings.map((f) => f.rule_id)).toEqual(['syntax-check', 'expression']);
  });

  it('carries file, line and snippet', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    const first = findings[0];
    expect(first?.file_path).toBe('.github/workflows/ci.yml');
    expect(first?.line_start).toBe(3);
    expect(first?.line_end).toBe(3);
    expect(first?.snippet).toContain('branch: main');
  });

  it('title is the message', () => {
    const { findings } = actionlintParser.parse(SAMPLE);
    expect(findings[0]?.title).toContain('unexpected key "branch"');
  });

  it('skips an entry with no filepath (malformed input), never throws', () => {
    const { findings } = actionlintParser.parse(JSON.stringify([{ message: 'oops', line: 1, kind: 'syntax-check' }]));
    expect(findings).toEqual([]);
  });

  it('skips an entry with no message, never throws', () => {
    const { findings } = actionlintParser.parse(JSON.stringify([{ filepath: 'x.yml', line: 1, kind: 'syntax-check' }]));
    expect(findings).toEqual([]);
  });

  it('returns no findings on null input (an empty successful run serializes to `null`, not `[]`)', () => {
    expect(actionlintParser.parse('null').findings).toEqual([]);
  });

  it('returns no findings on empty array input', () => {
    expect(actionlintParser.parse('[]').findings).toEqual([]);
  });

  it('returns no findings on unparseable input rather than throwing', () => {
    expect(actionlintParser.parse('not json').findings).toEqual([]);
  });
});
