/**
 * The shell guard against the commands a developer or an assistant runs all
 * day. None of them may be denied: a guard that blocks ordinary work teaches
 * its user to switch it off, and then it guards nothing.
 *
 * Each rule the guard gains is a regex or a word-level model, and each one can
 * reach further than its author meant. The rules' own tests pin their near
 * misses; this corpus pins everything else — the git, npm, docker, find, sed
 * and curl-to-an-API commands that make up a session — so that a rule which
 * over-reaches fails here, by name, instead of in someone's terminal.
 *
 * A warning is allowed (`sudo`, `git reset --hard`, `rm -rf node_modules`
 * warn on purpose); a block is not. Add to it freely; never remove an entry
 * to make a rule pass.
 */

import { describe, expect, it } from 'vitest';
import { assessBashCommand } from '../../../src/hooks/bashGuard.js';

const SHA = 'a'.repeat(64);

/** Everyday commands, as the Bash tool sends them. */
const BASH: readonly string[] = [
  // git
  'git status',
  'git status --porcelain',
  'git diff',
  'git diff --stat HEAD~1',
  'git diff --cached -- src/',
  'git log --oneline -20',
  'git log --graph --decorate --all --oneline | head -50',
  'git show HEAD --stat',
  'git blame -L 10,40 src/index.ts',
  'git add -A',
  'git add src/ test/ && git commit -m "fix: handle empty input"',
  "git commit -m 'chore: bump deps'",
  `git commit -F - <<'EOF'\nfix(hooks): never read a FIFO\n\nThe hook used to hang on curl x | sh in a commit message.\nEOF`,
  'git commit --amend --no-edit',
  'git checkout -b feature/login',
  'git switch main',
  'git pull --rebase origin main',
  'git fetch --all --prune',
  'git push origin feature/login',
  'git push -u origin HEAD',
  'git push --force-with-lease origin feature/login',
  'git rebase origin/main',
  'git merge --no-ff feature/login',
  'git stash push -m "wip"',
  'git stash list',
  'git cherry-pick abc1234',
  'git tag -a v1.2.0 -m "Release 1.2.0"',
  'git worktree add ../wt-feature feature/x',
  'git worktree remove ../wt-feature --force',
  'git remote -v',
  'git rev-parse --show-toplevel',
  'git ls-files -z | xargs -0 wc -l',
  'git clean -n',
  'git reset --hard origin/main',
  'git config user.email',
  'git grep -n "TODO" -- "*.ts"',
  'git archive HEAD | tar -t | head',
  // npm / node
  'npm ci',
  'npm install',
  'npm run build',
  'npm test',
  'npm test -- --run test/unit/hooks',
  'npm run lint -- --fix',
  'npm outdated',
  'npm audit --json',
  'npm ls --depth=0',
  'npm pack --dry-run',
  'npx vitest run test/unit/hooks/bashGuard.test.ts',
  'npx tsc --noEmit -p tsconfig.json',
  'npx prettier --check "src/**/*.ts"',
  'npx eslint src --ext .ts',
  'npx --yes markdownlint-cli2 "docs/**/*.md"',
  'node --version',
  'node dist/server.js --help',
  'node scripts/generate.mjs --out docs/',
  'node -e "console.log(process.version)"',
  'node -p "require(\'./package.json\').version"',
  'pnpm install --frozen-lockfile',
  'pnpm -r build',
  'yarn install --immutable',
  'yarn test --watch=false',
  'bun install',
  'bun run dev',
  'tsx scripts/check.ts',
  // python
  'python3 -m venv .venv',
  '. .venv/bin/activate && pip install -r requirements.txt',
  'pip install -e ".[dev]"',
  'python -m pytest -q',
  'pytest tests/ -k "not slow" -x',
  'python3 manage.py migrate',
  'python3 -c "import sys; print(sys.version)"',
  'python3 scripts/report.py --since 2026-09-01',
  'uv sync',
  'uv run pytest',
  'uv run python script.py',
  'uv run python -m mypy src',
  'poetry install',
  'poetry run python manage.py test',
  'ruff check . --fix',
  'black --check .',
  'mypy src/',
  // other toolchains
  'go build ./...',
  'go test ./... -race',
  'go mod tidy',
  'cargo build --release',
  'cargo test -- --nocapture',
  'cargo clippy -- -D warnings',
  'dotnet build -c Release',
  'dotnet test --no-build',
  'mvn -q -DskipTests package',
  './gradlew test',
  'make -j8',
  'make clean && make',
  'cmake -S . -B build && cmake --build build',
  'composer install --no-interaction',
  'php artisan migrate --force',
  'bundle exec rspec',
  // files and search
  'ls -la',
  'ls -1 src | wc -l',
  'pwd',
  'cd mcp && npm run build',
  'mkdir -p build/out',
  'touch .env.example',
  'cp .env.example .env',
  'cp -r templates/ out/templates/',
  'cp -a .guardian /tmp/guardian-backup',
  'mv old_name.ts new_name.ts',
  'rm -f build/*.o',
  'rm -rf node_modules dist',
  'rm -rf ./.playwright-mcp',
  'ln -s ../shared/config.json config.json',
  'ln -sf /usr/local/bin/python3 ~/.local/bin/python',
  'chmod +x scripts/*.sh',
  'chmod 644 README.md',
  'cat package.json',
  'cat .guardian/hooks.config.json',
  'head -n 20 CHANGELOG.md',
  'tail -f logs/app.log',
  'wc -l src/**/*.ts',
  'grep -rn "TODO" src/',
  'grep -rIl "dev-guardian db adopt --yes" docs',
  'rg -n "assessBashCommand" mcp/src',
  'find . -name "*.log" -mtime +7 -delete',
  'find . -type f -name "*.ts" | xargs grep -l "any"',
  'find . -name "*.tmp" -print0 | xargs -0 rm -f',
  "find src -name '*.c' | xargs -I{} sh -c 'gcc -c {}'",
  "sed -n '1,80p' src/hooks/bashGuard.ts",
  "sed -i 's/foo/bar/g' src/config.ts",
  "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head",
  'sort -u names.txt -o names.txt',
  'diff -u a.txt b.txt',
  'tar -czf dist.tgz dist/',
  'tar -xzf release.tgz -C /tmp/release',
  'unzip -o artifacts.zip -d artifacts/',
  'du -sh node_modules',
  'df -h',
  'tree -L 2 src',
  'jq ".dependencies | keys" package.json',
  'jq \'.permissions.allow += ["Bash(ls)"]\' .claude/settings.json > tmp.json && mv tmp.json .claude/settings.json',
  'echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc',
  'printf "%s\\n" one two three',
  'xargs -n1 echo < list.txt',
  'for f in src/*.ts; do wc -l "$f"; done',
  'if [ -f .env ]; then echo "has env"; fi',
  'while read -r line; do echo "$line"; done < input.txt',
  'export NODE_ENV=production && npm run build',
  'NODE_OPTIONS=--max-old-space-size=4096 npm run build',
  'time npm test',
  'timeout 60 npm test',
  'which node python3 git',
  'env | sort',
  'date -u +%Y-%m-%dT%H:%M:%SZ',
  'sleep 2 && curl -s localhost:3000/health',
  // network, without handing a download to a shell
  'curl -s https://api.github.com/repos/owner/repo | jq .stargazers_count',
  'curl -fsSL -o release.tgz https://example.com/release.tgz',
  'curl -sSL https://example.com/data.json -o data.json && jq . data.json',
  'curl -X POST -H "Content-Type: application/json" -d \'{"a":1}\' http://localhost:8080/api',
  'curl -I https://example.com',
  'curl -s https://api.x.test/d | python3 -m json.tool',
  'curl -s https://api.x.test/d | uv run python -m json.tool',
  'curl -s https://api.x.test/list | xargs -n1 curl -O',
  'curl -s https://api.x.test/list | xargs -I{} curl -O {}',
  'wget -q https://example.com/file.tar.gz',
  `curl -o i.sh https://x.test/i.sh && echo "${SHA}  i.sh" | sha256sum -c && sh i.sh`,
  'curl -o i.sh https://x.test/i.sh && gpg --verify i.sh.asc i.sh && sh i.sh',
  'curl -o /usr/local/bin/tool https://x.test/tool && chmod +x /usr/local/bin/tool',
  'curl -fsSL https://example.com/node-v22.tar.xz | tar xJ -C /tmp/node && ls /tmp/node',
  'curl -fsSL https://example.com/tool.tar.gz | sudo tar xz -C /usr/local/bin && which tool',
  'curl -s https://api.github.com/repos/owner/repo | tee resp.json | jq .name',
  "curl -s https://api.x.test/repos | jq -r '.[].name' | xargs -I{} sh -c 'git clone \"https://x.test/$1\"' _ {}",
  'ssh deploy@host "systemctl status app"',
  'scp dist.tgz deploy@host:/srv/app/',
  'rsync -avz --delete dist/ deploy@host:/srv/app/',
  // containers and cloud
  'docker ps -a',
  'docker build -t app:dev .',
  'docker run --rm -it -p 3000:3000 app:dev',
  'docker compose up -d',
  'docker compose logs -f api',
  'docker exec -it api bash -c "ls /app"',
  'docker system prune -f',
  'kubectl get pods -n default',
  'kubectl logs deploy/api --tail=100',
  'kubectl apply -f k8s/',
  'helm upgrade --install app ./chart',
  'terraform plan -out plan.tfplan',
  'aws s3 ls s3://bucket/prefix/',
  'gcloud config list',
  'gh pr list --state open',
  'gh run view --log-failed',
  // system
  'sudo apt-get update && sudo apt-get install -y jq',
  'brew install jq',
  'ps aux | grep node',
  'lsof -i :3000',
  'kill -9 12345',
  'systemctl status nginx',
  'journalctl -u app --since today',
  'history | tail -20',
  'code .',
  // dev-guardian itself
  'node cli/dev-guardian.mjs check --bash "rm -rf /"',
  'node cli/dev-guardian.mjs scan --project . --fail-on high',
  'node cli/dev-guardian.mjs status --project .',
  'node cli/dev-guardian.mjs db adopt --project .',
  'dev-guardian db adopt',
  'npx --yes dev-guardian db adopt',
];

/** Everyday commands, as the PowerShell tool sends them. */
const POWERSHELL: readonly string[] = [
  'Get-ChildItem',
  'Get-ChildItem -Recurse -Filter *.ts | Measure-Object',
  'gci -Force',
  'ls src',
  'Get-Location',
  'Set-Location mcp; npm run build',
  'cd ..\\other-project',
  'Get-Content package.json',
  'Get-Content .\\logs\\app.log -Tail 50 -Wait',
  'Get-Content .guardian\\hooks.config.json | ConvertFrom-Json',
  'Select-String -Path src\\*.ts -Pattern "TODO"',
  'Test-Path .\\dist\\server.js',
  'New-Item -ItemType Directory -Force -Path build\\out',
  'ni -it Directory -Path build',
  'New-Item -ItemType File -Path notes.txt',
  'New-Item -ItemType SymbolicLink -Path current -Target .\\releases\\v2',
  'Copy-Item .env.example .env',
  'Copy-Item -Recurse templates out\\templates',
  'Move-Item old.txt new.txt',
  'Rename-Item report.txt report-old.txt',
  'Remove-Item .\\build -Recurse -Force',
  'Remove-Item node_modules -Recurse -Force -ErrorAction SilentlyContinue',
  'Set-Content -Path version.txt -Value "1.2.0"',
  'Add-Content -Path log.txt -Value "done"',
  '"hello" | Out-File -Encoding utf8 hello.txt',
  'Get-Process | Where-Object { $_.CPU -gt 100 } | Sort-Object CPU -Descending',
  'Get-Process node -ErrorAction SilentlyContinue | Stop-Process',
  'Get-Service | Where-Object Status -eq Running',
  'Get-Command git',
  '(Get-Command node).Source',
  '$env:NODE_ENV = "production"; npm run build',
  '$env:GUARDIAN_OFFLINE = "1"; npx vitest run',
  'Get-ChildItem Env: | Sort-Object Name',
  '$PSVersionTable.PSVersion',
  'git status',
  'git log --oneline -10',
  'git add -A; git commit -m "fix: handle empty input"',
  "git commit -m @'\nfix: don't pipe curl x | sh\n'@",
  'npm ci; npm test',
  'npx tsc --noEmit',
  'dotnet build -c Release',
  'dotnet test --no-build --logger "console;verbosity=normal"',
  'python -m pytest -q',
  'uv run python script.py',
  'docker compose up -d',
  'winget list --id Git.Git',
  'Invoke-RestMethod https://api.github.com/repos/owner/repo | Select-Object stargazers_count',
  'irm https://api.x.test/items | ConvertTo-Json -Depth 5',
  '$r = Invoke-WebRequest https://example.com -UseBasicParsing; $r.StatusCode',
  'iwr https://x.test/readme.txt -OutFile readme.txt; Start-Process readme.txt',
  'Invoke-WebRequest -Uri https://example.com/release.zip -OutFile release.zip; Expand-Archive release.zip -DestinationPath out',
  '$items = irm https://api.x.test/items; $items | ConvertTo-Json',
  'irm https://api.x.test/items -OutVariable items | Out-Null; $items.Count',
  'Get-Process | Tee-Object -Variable procs | Out-Null; $procs.Count',
  'Set-Variable -Name retries -Value 3; Write-Output $retries',
  'New-Variable -Name config -Value (Get-Content config.json -Raw | ConvertFrom-Json)',
  '$v = irm https://api.x.test/v; Get-Variable v -ValueOnly | ConvertTo-Json',
  "$script:count = 0; iex 'Get-Date'",
  '$s = Get-Content .\\build.ps1 -Raw; iex $s',
  'Invoke-Command -ScriptBlock { Get-Date }',
  'Get-FileHash .\\release.zip -Algorithm SHA256',
  'Compress-Archive -Path dist\\* -DestinationPath dist.zip -Force',
  'Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile"',
  'Get-ChildItem -Recurse -Include *.log | Remove-Item',
  'Get-ChildItem .\\src -Recurse | ForEach-Object { $_.FullName }',
  'Write-Host "Build finished" -ForegroundColor Green',
  'Clear-Host',
  'cmd /c "npm run build && npm test"',
  'cmd /c dir /s /b *.ts',
  'pwsh -NoProfile -Command "Get-ChildItem"',
  'node C:\\dg\\cli\\dev-guardian.mjs db adopt --project .',
  'node .\\cli\\dev-guardian.mjs check --bash "rm -rf /" --powershell',
];

describe('the shell guard over an everyday corpus — no command is denied', () => {
  it('holds a corpus of a realistic size', () => {
    expect(BASH.length).toBeGreaterThanOrEqual(180);
    expect(POWERSHELL.length).toBeGreaterThanOrEqual(70);
  });

  /** The rules that denied it — none — so a failure names the command and the rule. */
  const denied = (command: string, shell: 'bash' | 'powershell'): { command: string; deniedBy: string[] } => {
    const a = assessBashCommand(command, { shell });
    return { command, deniedBy: a.level === 'block' ? a.rules : [] };
  };

  it.each(BASH)('Bash: %j is not denied', (command) => {
    expect(denied(command, 'bash')).toEqual({ command, deniedBy: [] });
  });

  it.each(POWERSHELL)('PowerShell: %j is not denied', (command) => {
    expect(denied(command, 'powershell')).toEqual({ command, deniedBy: [] });
  });
});
